ngx-kmp-push: rename to ngx-kmp-out
for consistency with ngx-kmp-in

diff --git a/nginx-mpegts-kmp-module/config b/nginx-mpegts-kmp-module/config
--- a/nginx-mpegts-kmp-module/config
+++ b/nginx-mpegts-kmp-module/config
@@ -1,19 +1,19 @@
 ngx_addon_name=ngx_ts_kmp_module
 
-# ngx_kmp_push_module dependency
+# ngx_kmp_out_module dependency
 #
 if test -n "$ngx_module_link"; then
-    if test -n "$KMP_PUSH_CORE_SRCS"; then
-        echo "found ngx_kmp_push_module for $ngx_addon_name; looks good."
+    if test -n "$KMP_OUT_CORE_SRCS"; then
+        echo "found ngx_kmp_out_module for $ngx_addon_name; looks good."
     else
-        echo "error: ngx_kmp_push_module is required to build $ngx_addon_name; please put it before $ngx_addon_name." 1>&2
+        echo "error: ngx_kmp_out_module is required to build $ngx_addon_name; please put it before $ngx_addon_name." 1>&2
         exit 1
     fi
 else
-    if echo $NGX_ADDON_SRCS | grep " ngx_kmp_push_module" > /dev/null; then
-        echo "found ngx_kmp_push_module for $ngx_addon_name; looks good."
+    if echo $NGX_ADDON_SRCS | grep " ngx_kmp_out_module" > /dev/null; then
+        echo "found ngx_kmp_out_module for $ngx_addon_name; looks good."
     else
-        echo "error: ngx_kmp_push_module is required to build $ngx_addon_name; please put it before $ngx_addon_name." 1>&2
+        echo "error: ngx_kmp_out_module is required to build $ngx_addon_name; please put it before $ngx_addon_name." 1>&2
         exit 1
     fi
 fi
